In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.stats import sem
import random
from scipy.stats import linregress
from sklearn import datasets
import scipy.stats as sts
import requests
import time
from scipy.stats import linregress

In [2]:
# File to Load (Remember to Change These)
file= "kansas-history.csv"

# Read Purchasing File and store into Pandas data frame
df= pd.read_csv(file)

In [8]:
df.head(20)

,date,state,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2/25/2021,KS,4724.0,NaN,0,NaN,9189.0,9189.0,214.0,0,...,1248768,0,NaN,573408.0,NaN,NaN,1248768.0,0,2438740.0,0
1,2/24/2021,KS,4724.0,NaN,81,NaN,9189.0,9189.0,214.0,86,...,1248768,5269,NaN,573408.0,NaN,NaN,1248768.0,5269,2438740.0,19844
2,2/23/2021,KS,4643.0,NaN,0,NaN,9103.0,9103.0,214.0,0,...,1243499,0,NaN,563612.0,NaN,NaN,1243499.0,0,2418896.0,0
3,2/22/2021,KS,4643.0,NaN,29,NaN,9103.0,9103.0,214.0,32,...,1243499,5076,NaN,563612.0,NaN,NaN,1243499.0,5076,2418896.0,15821
4,2/21/2021,KS,4614.0,NaN,0,NaN,9071.0,9071.0,290.0,0,...,1238423,0,NaN,558292.0,NaN,NaN,1238423.0,0,2403075.0,0
5,2/20/2021,KS,4614.0,NaN,0,NaN,9071.0,9071.0,290.0,0,...,1238423,0,NaN,558292.0,NaN,NaN,1238423.0,0,2403075.0,0
6,2/19/2021,KS,4614.0,NaN,93,NaN,9071.0,9071.0,290.0,69,...,1238423,9125,NaN,558292.0,NaN,NaN,1238423.0,9125,2403075.0,20552
7,2/18/2021,KS,4521.0,NaN,0,NaN,9002.0,9002.0,300.0,0,...,1229298,0,NaN,543223.0,NaN,NaN,1229298.0,0,2382523.0,0
8,2/17/2021,KS,4521.0,NaN,115,NaN,9002.0,9002.0,300.0,79,...,1229298,5066,NaN,543223.0,NaN,NaN,1229298.0,5066,2382523.0,17858
9,2/16/2021,KS,4406.0,NaN,0,NaN,8923.0,8923.0,279.0,0,...,1224232,0,NaN,534602.0,NaN,NaN,1224232.0,0,2364665.0,0
10,2/15/2021,KS,4406.0,NaN,42,NaN,8923.0,8923.0,279.0,36,...,1224232,6643,NaN,534602.0,NaN,NaN,1224232.0,6643,2364665.0,18212
11,2/14/2021,KS,4364.0,NaN,0,NaN,8887.0,8887.0,348.0,0,...,1217589,0,NaN,527485.0,NaN,NaN,1217589.0,0,2346453.0,0
12,2/13/2021,KS,4364.0,NaN,0,NaN,8887.0,8887.0,348.0,0,...,1217589,0,NaN,527485.0,NaN,NaN,1217589.0,0,2346453.0,0
13,2/12/2021,KS,4364.0,NaN,61,NaN,8887.0,8887.0,348.0,47,...,1217589,6096,NaN,527485.0,NaN,NaN,1217589.0,6096,2346453.0,21097
14,2/11/2021,KS,4303.0,NaN,0,NaN,8840.0,8840.0,377.0,0,...,1211493,0,NaN,NaN,NaN,NaN,1211493.0,0,2325356.0,0
15,2/10/2021,KS,4303.0,NaN,106,NaN,8840.0,8840.0,377.0,91,...,1211493,7734,NaN,NaN,NaN,NaN,1211493.0,7734,2325356.0,23909
16,2/9/2021,KS,4197.0,NaN,0,NaN,8749.0,8749.0,319.0,0,...,1203759,0,NaN,NaN,NaN,NaN,1203759.0,0,2301447.0,0
17,2/8/2021,KS,4197.0,NaN,96,NaN,8749.0,8749.0,319.0,69,...,1203759,6706,NaN,NaN,NaN,NaN,1203759.0,6706,2301447.0,18488
18,2/7/2021,KS,4101.0,NaN,0,NaN,8680.0,8680.0,526.0,0,...,1197053,0,NaN,NaN,NaN,NaN,1197053.0,0,2282959.0,0
19,2/6/2021,KS,4101.0,NaN,0,NaN,8680.0,8680.0,526.0,0,...,1197053,0,NaN,NaN,NaN,NaN,1197053.0,0,2282959.0,0

In [7]:
df.count()

date                                357
state                               357
death                               349
deathConfirmed                        0
deathIncrease                       357
deathProbable                         0
hospitalized                        336
hospitalizedCumulative              336
hospitalizedCurrently               216
hospitalizedIncrease                357
inIcuCumulative                     303
inIcuCurrently                      226
negative                            357
negativeIncrease                    357
negativeTestsAntibody                 0
negativeTestsPeopleAntibody           0
negativeTestsViral                    0
onVentilatorCumulative              303
onVentilatorCurrently               226
positive                            357
positiveCasesViral                    0
positiveIncrease                    357
positiveScore                       357
positiveTestsAntibody                 0
positiveTestsAntigen                  0
positiveTestsPeopleAntibody           0
positiveTestsPeopleAntigen            0
positiveTestsViral                    0
recovered                             0
totalTestEncountersViral              0
totalTestEncountersViralIncrease    357
totalTestResults                    357
totalTestResultsIncrease            357
totalTestsAntibody                    0
totalTestsAntigen                    14
totalTestsPeopleAntibody              0
totalTestsPeopleAntigen               0
totalTestsPeopleViral               277
totalTestsPeopleViralIncrease       357
totalTestsViral                      30
totalTestsViralIncrease             357
dtype: int64